name: ssd_secure_app

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.8.9
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^10.2.0
  dio: ^4.0.6
  file_picker: ^5.2.2
    
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
